stages:
    - deploy

deploy:
    stage: deploy
    image: argoproj/argocd:v2.3.3
    services:
      - docker:dind
    script:
      - argocd --grpc-web --auth-token ${ARGO_TOKEN} --server ${ARGO_SERVER} --insecure app set ${ARGO_APP_NAME} -p backend.image.tag=latest
      - argocd --grpc-web --auth-token ${ARGO_TOKEN} --server ${ARGO_SERVER} --insecure app sync ${ARGO_APP_NAME}
    when: manual
    environment:
        name: kubernetes
        url: https://00-burunov-m.k8s.praktikum-services.tech/
