# Установка pre-commit: pip install pre-commit
# Установка hook в git: pre-commit install
# Создать файл .pre-commit-config.yaml
# pre-commit run --all-files

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    #-   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.2
    hooks:
    - id: gitlab-ci-linter
      files: '.gitlab-ci.custom.yml'
      args:
        - '--filename'
        - '.gitlab-ci.custom.yml'
