backend:
  # Вместо latest правильнее использовать версию .Chart.AppVersion в шаблоне
  image:
    repository: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-backend
    tag: latest
  replicas: 3
  service:
    port: 8080
    targetPort: 8080
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  startupProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 6
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

backend-report:
  image:
    repository: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-backend-report
    tag: latest
  replicas: 3
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: Recreate

frontend:
  image:
    repository: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-frontend
    tag: latest
  replicas: 3
  service:
    port: 80
    targetPort: 8080
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  strategy:
    type: Recreate
  fqdn: 00-burunov-m.k8s.praktikum-services.tech
  ingress:
    port: 80
