---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: backend-report
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment }}"
spec:
  replicas: "{{ .Values.replicas }}"
  revisionHistoryLimit: "{{ .Values.revisionHistoryLimit }}"
  strategy:
    type: "{{ .Values.strategy.type }}"
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: SPRING_CLOUD_VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: spring-cloud-vault-host
                  key: spring-cloud-vault-host
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spring-cloud-vault-token
                  key: spring-cloud-vault-token
            - name: VIRTUAL_HOST
              value: sausage-store-backend-report
          ports:
            - name: backend-report
              containerPort: "{{ .Values.service.targetPort }}"
      imagePullSecrets:
        - name: docker-config-secret
