---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-frontend:k8s-1
          imagePullPolicy: Always
          volumeMounts:
              - name: nginx-conf
                mountPath: /etc/nginx/conf.d/default.conf
                subPath: nginx.conf
                readOnly: true
          env:
            - name: SPRING_CLOUD_VAULT_HOST
              value: 51.250.7.70
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spring-cloud-vault-token
                  key: spring-cloud-vault-token
            - name: DEFAULT_HOST
              value: sausage-store-backend
          ports:
            - name: frontend
              containerPort: 8080
      imagePullSecrets:
        - name: docker-config-secret
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
