apiVersion: v1
kind: LimitRange
metadata:
  name: my-resource-limits
  namespace: betta-maksim-burunov
spec:
  limits:
    - type: Pod
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
    - type: Container
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "300m"
        memory: "4Mi"
      default:
        cpu: "500m"
        memory: "2Gi"
      defaultRequest:
        cpu: "500m"
        memory: "2Gi"
