---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 3
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: gitlab.praktikum-services.ru:5050/00_burunov_m/sausage-store/sausage-store-backend-report:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: 0.8
            limits:
              memory: "2048Mi"
              cpu: 0.9
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: spring-cloud-vault-host
                  key: spring-cloud-vault-host
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spring-cloud-vault-token
                  key: spring-cloud-vault-token
            - name: VIRTUAL_HOST
              value: sausage-store-backend-report
          ports:
            - name: backend-report
              containerPort: 8081
      imagePullSecrets:
        - name: docker-config-secret
